import React, { useState } from "react";
import styles from "../../styles/contact.module.css";
import NavBar from "@/components/NavBar";
import { EnvelopeIcon, PhoneIcon } from "@heroicons/react/24/outline";
import Image from "next/image";
import Footer from "@/components/Footer";
import Head from "next/head";
import axios from "axios";

const Index = () => {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [subject, setSubject] = useState("");
  const [message, setMessage] = useState("");
  const [successMessage, setSuccessMessage] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post("/api/contact", { name, email, subject, message }, { headers: { "Content-Type": "application/json" } });
      console.log(response.data); // Success message from the server
      setSuccessMessage("Email sent successfully.");
      // Reset form fields
      setName("");
      setEmail("");
      setSubject("")
      setMessage("");
    } catch (error) {
      console.error(error);
      // Handle error
    }
  };

  return (
    <>
      <Head>
        <title>Contact Us </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NavBar />
      <div className={styles.contactContainer}>
        <div className={styles.upperContainer}>
          <div className={styles.bgImageContainer}>
            <Image src="https://res.cloudinary.com/dbbtqwy3w/image/upload/v1686376744/zendora/bg_tcm4ex.png" alt='backgourndImage' fill />
          </div>
          <div className={styles.ourprofessionalContainer}>
            <h1>Contact us</h1>
            <div className={styles.pre}>
              <span>Home</span>/<span> Contact us</span>
            </div>
          </div>
        </div>
        <div className={styles.maxContainer}>
          <div className={styles.contactusContainer}>
            <div className={styles.contactLeft}>
              <h1>Contact Info</h1>
              <div>
                <div className={styles.uppp}><PhoneIcon className={styles.phoneIcon} /><span>Phone</span></div>
                <div className={styles.numContainer}>
                  <p>+1 312-808-1999</p> | <p>+1 233-688-8999</p>
                </div>
                <p>( This number is for leasing information purposes. Please allow 24 hours for a Zendora Associate to contact you )</p>
              </div>
              <div className={styles.emailContainer}>
                <div className={styles.bottom}><EnvelopeIcon className={styles.phoneIcon} /><span>Email</span></div>
                <p>INFO@ZENDORASALON.COM</p>
              </div>
            </div>
            <div className={styles.contactRight}>
              <h1>Get in Touch</h1>
              <form onSubmit={handleSubmit}>
                <input type="text" value={name} required onChange={(e) => setName(e.target.value)} placeholder="Your Name" />
                <input type="email" value={email} required onChange={(e) => setEmail(e.target.value)} placeholder="Your Email" />
                <input type="text" value={subject} required onChange={(e) => setSubject(e.target.value)} placeholder="Subject" />
                <textarea value={message} cols={30} rows={10} onChange={(e) => setMessage(e.target.value)} placeholder="Your Message"></textarea>
                <button>SEND MESSAGE</button>
              </form>
              {successMessage && <div className={styles.successMessage}>{successMessage}</div>}
            </div>
          </div>
        </div>
        <div className={styles.mapContainer}>
          <iframe
            className={styles.googleMap}
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3265.374059203626!2d-92.49589762427729!3d35.07238546317928!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x87cd7d0cc7198317%3A0x1a9de45bdf4663bc!2s3820%20Dave%20Ward%20Dr%2C%20Conway%2C%20AR%2072034%2C%20USA!5e0!3m2!1sen!2s!4v1685118865885!5m2!1sen!2s"
            allowfullscreen
            loading="lazy"
          ></iframe>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Index;
