import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/NavBar'
import Slider from '@/components/Slider'
import AboutC from '@/components/AboutC'
import WeAre from '@/components/WeAre'
import ImageGallery from '@/components/Gallery'
import Footer from '@/components/Footer'
import Professionals from '@/components/Professionals'


export default function Home() {
  return (
    <>
      <Head>
        <title>Zendora</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/faviconn.webp" />
      </Head>
       <main className={styles.main}>
        <NavBar/>
        <Slider/>
        <AboutC/>
        <WeAre/>
        <Professionals/>
        <ImageGallery/>
        <Footer/>
       </main>
    </>
  )
}
