import Footer from '@/components/Footer';
import NavBar from '@/components/NavBar';
import styles from '../../styles/bookappointment.module.css';
import React, { useState } from 'react';
import Image from 'next/image';
import Head from 'next/head';
import axios from 'axios';

const Index = () => {
  const [name, setName] = useState('');
  const [phone, setPhone] = useState('');
  const [address, setAddress] = useState('');
  const [email, setEmail] = useState('');
  const [service, setService] = useState('');
  const [date, setDate] = useState('');
  const [message, setMessage] = useState('');
  const [successMessage, setSuccessMessage] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post('/api/bookappointment', {
        name,
        phone,
        address,
        email,
        service,
        date,
        message,
      });
      console.log(response.data); // Success message from the server
      setSuccessMessage('Appointment booked successfully.');
      // Reset form fields
      setName('');
      setPhone('');
      setAddress('');
      setEmail('');
      setService('');
      setDate('');
      setMessage('');
    } catch (error) {
      console.error(error);
      // Handle error
    }
  };

  return (
    <>
      <Head>
        <title>Book an Appointment </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NavBar />
      <div className={styles.upperContainer}>
        <div className={styles.bgImageContainer}>
          <Image src="https://res.cloudinary.com/dbbtqwy3w/image/upload/v1686376744/zendora/bg_tcm4ex.png" alt="backgourndImage" fill />
        </div>
        <div className={styles.ourprofessionalContainer}>
          <h1>Book an Appointment</h1>
          <div className={styles.pre}>
            <span>Home</span>/<span> Book An Appointment</span>
          </div>
        </div>
      </div>
      <div className={styles.appointContainer}>
        <form onSubmit={handleSubmit}>
          <div className={styles.flexItem}>
            <input
              required
              type="text"
              placeholder="Name"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
            <input
              required
              type="text"
              placeholder="Phone"
              value={phone}
              onChange={(e) => setPhone(e.target.value)}
            />
          </div>
          <div className={styles.flexItem}>
            <input
              required
              type="text"
              placeholder="Your Address"
              value={address}
              onChange={(e) => setAddress(e.target.value)}
            />
            <input
              required
              type="text"
              placeholder="Your Email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>
          <div className={styles.flexItem}>
            <select
              required
              value={service}
              onChange={(e) => setService(e.target.value)}
            >
              <option value="">Select a service</option>
              <option value="Spa">Spa</option>
              <option value="Massage">Massage</option>
              <option value="Salon">Salon</option>
              <option value="Barber">Barber</option>
            </select>
            <input
              required
              type="date"
              placeholder="Date"
              value={date}
              onChange={(e) => setDate(e.target.value)}
            />
          </div>
          <div className={styles.messageContainer}>
            <textarea
              required
              placeholder="Message"
              value={message}
              onChange={(e) => setMessage(e.target.value)}
            />
          </div>
          <button type="submit">SEND</button>
        </form>
        {successMessage && <p className={styles.mymessage}>{successMessage}</p>}
      </div>
      <Footer />
    </>
  );
};

export default Index;
